// ingredients
export const GET_ITEMS_REQUEST = "GET_ITEMS_REQUEST";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAILED = "GET_ITEMS_FAILED";

// order
export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILED = "GET_ORDER_FAILED";

export const DELETE_CURRENT_ORDER = "DELETE_CURRENT_ORDER";

// modal
export const OPEN_ORDER_MODAL = "OPEN_ORDER_MODAL";
export const CLOSE_ORDER_MODAL = "CLOSE_ORDER_MODAL";

export const OPEN_ERR_MODAL = "OPEN_ERR_MODAL";
export const CLOSE_ERR_MODAL = "CLOSE_ERR_MODAL";

export const SET_ERR = "SET_ERR";

// selected-items
export const ADD_SELECTED_BUN = "ADD_SELECTED_BUN";
export const ADD_SELECTED_TOPPING = "ADD_SELECTED_TOPPING";

export const DELETE_SELECTED_BUNS = "DELETE_SELECTED_BUNS";
export const DELETE_SELECTED_TOPPINGS = "DELETE_SELECTED_TOPPINGS";

export const DELETE_SELECTED_TOPPING = "DELETE_SELECTED_TOPPING";

export const SORT_TOPPING = "SORT_TOPPING";

// user
export const SET_USER_REQUEST = "SET_USER_REQUEST";
export const SET_USER_SUCCESS = "SET_USER_SUCCESS";
export const SET_USER_FAILED = "SET_USER_FAILED";

export const AUTHORIZE_REQUEST = "AUTHORIZE_REQUEST";
export const AUTHORIZE_SUCCESS = "AUTHORIZE_SUCCESS";
export const AUTHORIZE_FAILED = "AUTHORIZE_FAILED";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

export const UPDATE_TOKEN_REQUEST = "UPDATE_TOKEN_REQUEST";
export const UPDATE_TOKEN_SUCCESS = "UPDATE_TOKEN_SUCCESS";
export const UPDATE_TOKEN_FAILED = "UPDATE_TOKEN_FAILED";

// password
export const SET_FORGOT_PASSWORD_REQUEST = "SET_FORGOT_PASSWORD_REQUEST";
export const SET_FORGOT_PASSWORD_SUCCESS = "SET_FORGOT_PASSWORD_SUCCESS";
export const SET_FORGOT_PASSWORD_FAILED = "SET_FORGOT_PASSWORD_FAILED";

export const SET_RESET_PASSWORD_REQUEST = "SET_FORGOT_PASSWORD_REQUEST";
export const SET_RESET_PASSWORD_SUCCESS = "SET_FORGOT_PASSWORD_SUCCESS";
export const SET_RESET_PASSWORD_FAILED = "SET_FORGOT_PASSWORD_FAILED";

// button
export const SET_BTN_DISABLED = "SET_BTN_DISABLED";
export const SET_BTN_ACTIVE = "SET_BTN_ACTIVE";

// tab
export const TAB_SWITCH = "TAB_SWITCH";
