export const OPEN_INGREDIENT_MODAL = "OPEN_INGREDIENT_MODAL";
export const CLOSE_INGREDIENT_MODAL = "CLOSE_INGREDIENT_MODAL";

export const OPEN_ORDER_MODAL = "OPEN_ORDER_MODAL";
export const CLOSE_ORDER_MODAL = "CLOSE_ORDER_MODAL";

export const OPEN_ERR_MODAL = "OPEN_ERR_MODAL";
export const CLOSE_ERR_MODAL = "CLOSE_ERR_MODAL";

export const SET_ERR = "SET_ERR";
