export const ADD_SELECTED_BUN = "ADD_SELECTED_BUN";
export const ADD_SELECTED_TOPPING = "ADD_SELECTED_TOPPING";

export const DELETE_SELECTED_BUNS = "DELETE_SELECTED_BUNS";
export const DELETE_SELECTED_TOPPINGS = "DELETE_SELECTED_TOPPINGS";

export const DELETE_SELECTED_TOPPING = "DELETE_SELECTED_TOPPING";

export const SORT_TOPPING = "SORT_TOPPING";
